name: Run Flask Container on EC2

on:
  workflow_run:

    workflows:
      - Deploy Flask App with Terraform

    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:

  run-docker:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: Download Terraform Outputs

        uses: actions/download-artifact@v4

        with:
          name: deploy

          path: ./outputs

          github-token: ${{ secrets.GITHUB_TOKEN }}

          run-id: ${{ github.event.workflow_run.id }}


      - name: Parse Terraform Outputs

        run: |

          DB_HOST=$(jq -r '.db_endpoint.value' ./outputs/terraform_outputs.json)

          EC2_IP=$(jq -r '.ec2_public_ip.value' ./outputs/terraform_outputs.json)

          ECR_REPO=$(jq -r '.ecr_repo_url.value' ./outputs/terraform_outputs.json)

          ALB_DNS=$(jq -r '.alb_dns.value' ./outputs/terraform_outputs.json)

          echo "DB_HOST=$DB_HOST" >> "$GITHUB_ENV"

          echo "EC2_IP=$EC2_IP" >> "$GITHUB_ENV"

          echo "ECR_REPO=$ECR_REPO" >> "$GITHUB_ENV"

          echo "ALB_DNS=$ALB_DNS" >> "$GITHUB_ENV"


      - name: Setup SSH Key

        run: |

          echo "${{ secrets.EC2_SSH_KEY }}" > fbkey.pem

          chmod 600 fbkey.pem


      - name: Deploy Docker Container to EC2

        env:

          DB_USERNAME: ${{ secrets.DB_USERNAME }}

          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        run: |

          ssh \
            -o StrictHostKeyChecking=no \
            -i fbkey.pem \
            ubuntu@${EC2_IP} << EOF

            set -e

            echo "Starting Docker..."

            sudo systemctl enable docker

            sudo systemctl start docker

            echo "Checking AWS CLI..."

            aws --version

            echo "Logging in to ECR..."

            aws ecr get-login-password \
              --region us-east-1 \
              | sudo docker login \
              --username AWS \
              --password-stdin ${ECR_REPO}

            echo "Pulling Flask image..."

            sudo docker pull ${ECR_REPO}:latest

            echo "Removing old Flask container..."

            sudo docker rm -f flask-app || true

            echo "Starting Flask application..."

            sudo docker run -d \
              --name flask-app \
              -p 5001:5000 \
              -e DB_HOST="${DB_HOST}" \
              -e DB_NAME="greetings_db" \
              -e DB_USER="${DB_USERNAME}" \
              -e DB_PASS="${DB_PASSWORD}" \
              ${ECR_REPO}:latest

            echo "Deployment completed."

            sudo docker ps

          EOF
